
# server.port=8181  # properties
server:
  port: 8181

#spring.datasource.url=xxx
#spring.datasource.username=xxx
#spring.datasource.password=xxx
#spring:
#  datasource:
#    url: xxx
#    username: xxx
#    password: xxx
